<a href="https://colab.research.google.com/github/mmarin11/Colabfiles/blob/main/Practica4/Practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Crear dos matrices de 3x3 con números aleatorios entre 1 y 10
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Matriz A:\n", A)
print("Matriz B:\n", B)

# 1. Suma de matrices
suma = A + B
print("\nSuma A + B:\n", suma)

# 2. Resta (A - B)
resta = A - B
print("\nResta A - B:\n", resta)

# 3. Multiplicar la matriz A por 2
doble_A = A * 2
print("\nMatriz A * 2:\n", doble_A)

# 4. Multiplicación matricial (producto punto)
producto = A @ B   # también se puede usar np.dot(A, B)
print("\nProducto A x B:\n", producto)

Matriz A:
 [[10  4  8]
 [ 3  6  2]
 [ 6  7  9]]
Matriz B:
 [[ 3  5 10]
 [ 4  9  8]
 [ 6  5  4]]

Suma A + B:
 [[13  9 18]
 [ 7 15 10]
 [12 12 13]]

Resta A - B:
 [[ 7 -1 -2]
 [-1 -3 -6]
 [ 0  2  5]]

Matriz A * 2:
 [[20  8 16]
 [ 6 12  4]
 [12 14 18]]

Producto A x B:
 [[ 94 126 164]
 [ 45  79  86]
 [100 138 152]]
